import "./globals.css";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

// components listed in the body tag below will apply to every page on the website.

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  );
}
